name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: denolib/setup-deno@master
      with:
        deno-version: 0.36.0
    - name: Run tests
      run: |
        deno run --allow-env --allow-read ./test.js